backend:
  name: git-gateway

display_url: https://boite-a-envies.netlify.com/
media_folder: "src/assets/images"
public_folder: "/assets/images"

collections: # A list of collections the CMS should be able to edit
  - name: "produits" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Produits" # Used in the UI
    label_singular: "Produit" # Used in the UI, ie: "New Post"
    format: json
    description: >
      Pour la publication des articles sur le site
    folder: "_products"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string",required: true , tagname: "h1"}
      - {label: "Type", required: true, name: "prix", widget: "select", options: ["bracelet", "montre", "bijoux", "accessoire"]}
      - {label: "Photo", name: "image", widget: "image", required: true, tagname: ""}
      - {label: "Description", name: "description", widget: "text", required: true}
      - {label: "Taille", name: "taille", widget: "number"}
      - {label: "Prix", name: "prix", widget: "number", required: true}
