backend:
  name: git-gateway

display_url: https://boite-a-envies.netlify.com/
media_folder: "src/assets/images"

collections: # A list of collections the CMS should be able to edit
  - name: "bracelets" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Bracelets" # Used in the UI
    label_singular: "Bracelet" # Used in the UI, ie: "New Post"
    description: >
      Pour la publication des bracelets sur le site
    folder: "_bracelets"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Photo", name: "image", widget: "image", required: true, tagname: ""}
      - {label: "Taille", name: "taille", widget: "number"}
      - {label: "Prix", name: "prix", widget: "number"}
